---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-api
spec:
  selector:
    matchLabels:
      app: worker-api
  template:
    metadata:
      labels:
        app: worker-api
    spec:
      containers:
      - name: worker-api
        image: worker:1
        env:
        - name: WORKER
          value: "0"
        - name: REDIS_CONNECTION_URL
          value: "redis://redis-svc:6379/0"
        - name: PORT
          value: "3000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node
spec:
  selector:
    matchLabels:
      app: worker-node
  template:
    metadata:
      labels:
        app: worker-node
    spec:
      containers:
      - name: worker-node
        image: worker:1
        env:
        - name: WORKER
          value: "1"
        - name: REDIS_CONNECTION_URL
          value: "redis://redis-svc:6379/0"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: worker-api-svc
spec:
  selector:
    app: worker-api
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort

